node {
    def app

    environment {
    SVC_ACCOUNT_KEY = credentials('GC_KEY')
  }
    
    stage('Clone repository') {
        /* Clone the repository to our Jenkins Workspace */

        checkout scm
    }

    stage('Build image') {
        /* Below command specifies exactly like the command line */
    
        app = docker.build("gcr.io/nasalab-316914/javaapp1")
    }
    
    stage('Test image') {
        
        app.inside {
            sh 'echo "Tests passed"'
        }
    }
    
    stage('Push image to gcr') {
        
        sh 'echo $SVC_ACCOUNT_KEY | base64 -d > ./gcr/jenkins.json'
        sh 'pwd'
        sh 'gcloud auth activate-service-account nasa7733@nasalab-316914.iam.gserviceaccount.com --key-file=jenkins.json'
        /* Finally, we'll push the image with two tags:
         * First, the incremental build number from Jenkins
         * Second, the 'latest' tag.
         * Pushing multiple tags is cheap, as all the layers are reused. */
        sh 'docker push gcr.io/nasalab-316914/javaapp1'
    }
    
     
     
    }
